version: '3.4'

services:
  auth-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ENV: dev
    ports:
      - $AUTH_API_PORT:50051
    volumes:
      - .:/go/src/
    depends_on:
      - keycloak
    networks:
      - auth
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: authdb
      DB_DATABASE: $AUTHDB_DB
      DB_USER: $AUTHDB_USERNAME
      DB_SCHEMA: public
      DB_PASSWORD: $AUTHDB_PASSWORD
      KEYCLOAK_USER: $KEYCLOAK_USERNAME
      KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    depends_on:
      - authdb
    networks:
      - auth

  authdb:
    image: postgres
    volumes:
      - .pgauthdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $AUTHDB_DB
      POSTGRES_USER: $AUTHDB_USERNAME
      POSTGRES_PASSWORD: $AUTHDB_PASSWORD
    networks:
      - auth

networks:
  auth:
    driver: bridge
