version: '3.4'

services:
  # AUTH-SERVICE
  auth-service-test:
    build:
      context: .
      dockerfile: .docker/Dockerfile.test
      args:
        SERVICE: ./service/auth
    networks:
      - auth

  # TIME-RECORD-SERVICE
  time-record-service-test:
    build:
      context: .
      dockerfile: .docker/Dockerfile.test
      args:
        SERVICE: ./service/time-record
    environment:
      DB_URI: mongodb://trdb:27017
    depends_on:
      - trdb
    networks:
      - time-record

  trdb:
    image: mongo:4.4
    networks:
      - time-record

networks:
  auth:
    driver: bridge
  time-record:
    driver: bridge
