apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ghcr.io/patricksferraz/auth-service:develop-latest
        ports:
        - containerPort: 50051
        envFrom:
          - secretRef:
              name: auth-secret
          - configMapRef:
              name: auth-conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      imagePullSecrets:
        - name: regcred
