apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accounting-ingress
  labels:
      name: accounting-ingress
spec:
  rules:
  # - host: ""
  - http:
      paths:

      - pathType: Prefix
        path: "/auth"
        backend:
          service:
            name: auth-service
            port:
              number: 8080

      - pathType: Prefix
        path: "/time-record"
        backend:
          service:
            name: time-record-service
            port:
              number: 8080
