FROM golang:1.16-alpine AS builder

WORKDIR /go/src
ENV PATH="/go/bin:${PATH}"
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

COPY . .

ARG SERVICE
RUN go build -o main $SERVICE

FROM scratch AS runtime
COPY --from=builder /go/src/main /
ENTRYPOINT ["./main", "grpc"]
