name: Auth - Continuous Integration (CI)

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare
      id: prep
      run: |
        SERVICE=auth
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        DOCKER_IMAGE=ghcr.io/patricksferraz/${SERVICE}-service:${BRANCH_NAME}
        TAGS="${DOCKER_IMAGE}-${{ github.sha }},${DOCKER_IMAGE}-latest"
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=service::./service/${SERVICE}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to ghcr
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        file: .docker/Dockerfile.test
        build-args: >
          SERVICE=${{ steps.prep.outputs.service }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      if: github.event_name != 'pull_request'
      with:
        builder: ${{ steps.buildx.outputs.name }}
        file: .docker/Dockerfile.prod
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.prep.outputs.tags }}
        target: runtime
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        build-args: >
          SERVICE=${{ steps.prep.outputs.service }}

    - name: Image digest
      if: github.event_name != 'pull_request'
      run: echo ${{ steps.docker_build.outputs.digest }}
